/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKchar extends Token
{
    public TKchar()
    {
        super.setText("char");
    }

    public TKchar(int line, int pos)
    {
        super.setText("char");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKchar(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKchar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKchar text.");
    }
}
