/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKdo extends Token
{
    public TKdo()
    {
        super.setText("do");
    }

    public TKdo(int line, int pos)
    {
        super.setText("do");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKdo(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKdo(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKdo text.");
    }
}
