/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKnull extends Token
{
    public TKnull()
    {
        super.setText("null");
    }

    public TKnull(int line, int pos)
    {
        super.setText("null");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKnull(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKnull(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKnull text.");
    }
}
