/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKprivate extends Token
{
    public TKprivate()
    {
        super.setText("private");
    }

    public TKprivate(int line, int pos)
    {
        super.setText("private");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKprivate(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKprivate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKprivate text.");
    }
}
