/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKprotected extends Token
{
    public TKprotected()
    {
        super.setText("protected");
    }

    public TKprotected(int line, int pos)
    {
        super.setText("protected");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKprotected(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKprotected(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKprotected text.");
    }
}
