/* This file was generated by SableCC (http://www.sablecc.org/). */

package node;

import analysis.*;

@SuppressWarnings("nls")
public final class TKvoid extends Token
{
    public TKvoid()
    {
        super.setText("void");
    }

    public TKvoid(int line, int pos)
    {
        super.setText("void");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TKvoid(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKvoid(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKvoid text.");
    }
}
